### PR TITLE
Stop BluI from crashing uncontrollably when width and height are not …

### PR DESCRIPTION
**Pull request by MelanieT**
…set to proper values. Do the right thing instead and tell the user where he messed up.

Crashes are harder to debug than messages :)

### CODE REVIEW

**Comment by AaronShea** [comment]
Will be creating a new tested release soon, thanks!

**Comment by MelanieT** [comment]
Great. We have other issues with BLUI I may be able to help if you can help me first. See the forum, I can't get keyboard input on OSX and we also get a crash on recent SuSe Linux even when building from source. If I had more info on how to properly build for these platforms, I could chip in more.
In particular, I can't link Blu in Xcode 7 if Blu was built from source (using binary cef 2111 as you did).
On Linux, the editor crashes on load with an error in XOpenDisplay (double free error)
We're really trying to make this a multiplatform game but seem to be stuck on both these fronts.

**Comment by AaronShea** [comment]
It is recommended to cross-compile Linux builds from within a Windows environment.
That's odd about keyboard input on OSX though.

**Comment by MelanieT** [comment]
One of our developers works on a Linux machine, does that mean she can never us the editor while BLUI is part of our project? Also, how do I go about compiling the whole shebang for OSX? I can't debug (single step) this as long as I have to depend on a Google supplied binary without debug infos!

**Comment by AaronShea** [comment]
Unfortunately my time is very limited due to college at the moment. I don't have an OSX machine up here with me to test on, nor a Linux machine with a sufficient graphics card for testing. I will try to look into things when I can.

**Comment by MelanieT** [comment]
We have all that, all I need to know is how you built this on OSX, since you have instructions up but only for Windows.

**Comment by AaronShea** [comment]
You can follow the CEF3 auto build script here: 

https://bitbucket.org/chromiumembedded/cef/wiki/BranchesAndBuilding

But you also must apply the OSX patches located here: 
https://github.com/AaronShea/BluBrowser

To the CEF codebase

**Pull request merged**
