### PR TITLE
Revert "Remove unused class (files)"

### PR DESCRIPTION
**Pull request by AaronShea**
Reverts AaronShea/BLUI#25

Things break with this large change, (will no longer compile) I'll look into it personally

### CODE REVIEW

**Comment by Shammah** [comment]
You probably miss the call to `doBluMessageLoop`. You probably want to add this static method to `FBlu` and call `FBlu::doBluMessageLoop` from the blueprint function. You merge dbefore I got the chance to fix this /o\

**Comment by AaronShea** [comment]
Full output of compiler from my test project

```
1>x:\uep\mutablestate\plugins\blui\source\blu\public\BluEye.h(191): error C2143: syntax error : missing ';' before '<'
1>x:\uep\mutablestate\plugins\blui\source\blu\public\BluEye.h(191): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>x:\uep\mutablestate\plugins\blui\source\blu\public\BluEye.h(191): error C2238: unexpected token(s) preceding ';'
1>x:\uep\mutablestate\plugins\blui\source\blu\public\BluEye.h(198): error C2146: syntax error : missing ';' before identifier 'info'
1>x:\uep\mutablestate\plugins\blui\source\blu\public\BluEye.h(198): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>x:\uep\mutablestate\plugins\blui\source\blu\public\BluEye.h(199): error C2143: syntax error : missing ';' before '<'
1>x:\uep\mutablestate\plugins\blui\source\blu\public\BluEye.h(199): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>x:\uep\mutablestate\plugins\blui\source\blu\public\BluEye.h(199): error C2238: unexpected token(s) preceding ';'
1>x:\uep\mutablestate\plugins\blui\source\blu\public\BluEye.h(200): error C2146: syntax error : missing ';' before identifier 'browserSettings'
1>x:\uep\mutablestate\plugins\blui\source\blu\public\BluEye.h(200): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>x:\uep\mutablestate\plugins\blui\source\blu\public\BluEye.h(217): error C2146: syntax error : missing ';' before identifier 'mouse_event'
1>x:\uep\mutablestate\plugins\blui\source\blu\public\BluEye.h(217): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>x:\uep\mutablestate\plugins\blui\source\blu\public\BluEye.h(218): error C2146: syntax error : missing ';' before identifier 'key_event'
1>x:\uep\mutablestate\plugins\blui\source\blu\public\BluEye.h(218): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>X:\UEP\MutableState\Plugins\BLUI\Source\Blu/Public/RenderHandler.h(6): error C2504: 'CefRenderHandler' : base class undefined
1>X:\UEP\MutableState\Plugins\BLUI\Source\Blu/Public/RenderHandler.h(16): error C2061: syntax error : identifier 'CefRefPtr'
1>X:\UEP\MutableState\Plugins\BLUI\Source\Blu/Public/RenderHandler.h(18): error C2061: syntax error : identifier 'CefRefPtr'
1>X:\UEP\MutableState\Plugins\BLUI\Source\Blu/Public/RenderHandler.h(26): error C2143: syntax error : missing ';' before '}'
1>X:\UEP\MutableState\Plugins\BLUI\Source\Blu/Public/RenderHandler.h(26): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>X:\UEP\MutableState\Plugins\BLUI\Source\Blu/Public/RenderHandler.h(26): error C4183: 'IMPLEMENT_REFCOUNTING': missing return type; assumed to be a member function returning 'int'
1>X:\UEP\MutableState\Plugins\BLUI\Source\Blu/Public/RenderHandler.h(16): error C3668: 'RenderHandler::GetViewRect' : method with override specifier 'override' did not override any base class methods
1>X:\UEP\MutableState\Plugins\BLUI\Source\Blu/Public/RenderHandler.h(18): error C3668: 'RenderHandler::OnPaint' : method with override specifier 'override' did not override any base class methods
1>X:\UEP\MutableState\Plugins\BLUI\Source\Blu/Public/RenderHandler.h(30): error C2504: 'CefClient' : base class undefined
1>X:\UEP\MutableState\Plugins\BLUI\Source\Blu/Public/RenderHandler.h(41): error C2143: syntax error : missing ';' before '<'
1>X:\UEP\MutableState\Plugins\BLUI\Source\Blu/Public/RenderHandler.h(41): error C2433: 'BrowserClient::CefRefPtr' : 'virtual' not permitted on data declarations
1>X:\UEP\MutableState\Plugins\BLUI\Source\Blu/Public/RenderHandler.h(41): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>X:\UEP\MutableState\Plugins\BLUI\Source\Blu/Public/RenderHandler.h(42): error C2334: unexpected token(s) preceding '{'; skipping apparent function body
1>X:\UEP\MutableState\Plugins\BLUI\Source\Blu/Public/RenderHandler.h(46): error C2143: syntax error : missing ';' before '<'
1>X:\UEP\MutableState\Plugins\BLUI\Source\Blu/Public/RenderHandler.h(46): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>X:\UEP\MutableState\Plugins\BLUI\Source\Blu/Public/RenderHandler.h(46): error C2238: unexpected token(s) preceding ';'
1>X:\UEP\MutableState\Plugins\BLUI\Source\Blu/Public/RenderHandler.h(48): error C2143: syntax error : missing ';' before '<'
1>X:\UEP\MutableState\Plugins\BLUI\Source\Blu/Public/RenderHandler.h(48): error C2433: 'BrowserClient::CefRefPtr' : 'virtual' not permitted on data declarations
1>X:\UEP\MutableState\Plugins\BLUI\Source\Blu/Public/RenderHandler.h(48): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>X:\UEP\MutableState\Plugins\BLUI\Source\Blu/Public/RenderHandler.h(49): error C2334: unexpected token(s) preceding '{'; skipping apparent function body
1>X:\UEP\MutableState\Plugins\BLUI\Source\Blu/Public/RenderHandler.h(53): error C2061: syntax error : identifier 'CefRefPtr'
1>X:\UEP\MutableState\Plugins\BLUI\Source\Blu/Public/RenderHandler.h(59): error C2143: syntax error : missing ';' before '}'
1>X:\UEP\MutableState\Plugins\BLUI\Source\Blu/Public/RenderHandler.h(59): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>X:\UEP\MutableState\Plugins\BLUI\Source\Blu/Public/RenderHandler.h(59): error C4183: 'IMPLEMENT_REFCOUNTING': missing return type; assumed to be a member function returning 'int'
1>X:\UEP\MutableState\Plugins\BLUI\Source\Blu/Public/RenderHandler.h(53): error C3668: 'BrowserClient::OnProcessMessageReceived' : method with override specifier 'override' did not override any base class methods
1>X:\UEP\MutableState\Plugins\BLUI\Source\Blu/Public/RenderHandler.h(37): error C2614: 'BrowserClient' : illegal member initialization: 'm_renderHandler' is not a base or member
```

**Comment by Shammah** [comment]
Could you try a rebuild? You put some `#include`s in the removed files. I therefore had to put

```
-#if PLATFORM_WINDOWS
-#include "AllowWindowsPlatformTypes.h"
-#endif
-#include "include/cef_client.h"
-#include "include/cef_app.h"
-#if PLATFORM_WINDOWS
-#include "HideWindowsPlatformTypes.h"
-#endif
```

into the pre-compiled header. All you had to do was issue a rebuild, your compiler still used the old files I think.

**Comment by AaronShea** [comment]
Full rebuild still causes the same errors

**Pull request merged**
