### PR TITLE
fix: crash when call BluEye function in Editor

### PR DESCRIPTION
**Pull request by ArCorvus**

### CODE REVIEW

**Comment by AaronShea** [comment]
Could you be a bit more specific about what caused the crash?

**Comment by ArCorvus** [comment]
Hi Aaron,

Crash 100% reproducible when I run game in the Editor window ("Selected Viewport"). In this mode BluEye initialization is skipped and browser is not created. So call of any function that depends on browser leads to crash.
Here are lines from UBluEye::init():
```c++
void UBluEye::init()
{
	/** 
	 * We don't want this running in editor unless it's PIE
	 * If we don't check this, CEF will spawn infinit processes with widget components
	 **/
	if (GEngine)
	{
		if (GEngine->IsEditor() && !GWorld->IsPlayInEditor())
		{
			UE_LOG(LogBlu, Log, TEXT("Notice: not playing - Component Will Not Initialize"));
			return;
		}
	}
	...
```
Thus initialization is interrupted and variable **browser** is not initialized (NULL).
When I call for example function **IsBrowserLoading** I get *Memory Access Violation*.
```c++
bool UBluEye::IsBrowserLoading()
{
	return browser->IsLoading();
}
```
UE4.8.3

Thanks for such great plugin!)

**Comment by AaronShea** [comment]
Ah I see. I'm going to look into this issue a bit further to see if there's something else that can be done. Thanks for the report!

**Comment by AaronShea** [comment]
I'm not able to reproduce this crash. Playing in editor, simulating in editor, and playing in selected view-port are not crashing the demo

**Comment by ArCorvus** [comment]
I'll check in the Demo and try to reproduce it.

**Comment by AaronShea** [comment]
Currently the  public demo needs to be updated to 4.9 and BLUI 3.1. Locally I've tested in 4.9 and 4.8 (newest minor release)

**Comment by ArCorvus** [comment]
Here is a sample project. While I was making this sample, I have noticed that behavior is different when we create BluEye Instance in Construct and when we create Instance later on some Event. Crash is reproducing only in the second case.
I have removed ThirdParty folder from plugin to reduce the size. I am using BLUI 3.1 from Release (https://github.com/AaronShea/BLUI/releases/download/3.1/BLUI.3.1.Windows.Linux.CX.zip)
Sample: https://drive.google.com/open?id=0B9pKJqA0bh7SdVJ3ZXFOU3ZpY00

**Comment by AaronShea** [comment]
Seems I've figured out the issue. 
When you construct a new BluEye on Event Contract `GEngine->IsEditor()` and `GWorld->IsPlayInEditor()` return their expected values.

However:

When the editor is already running, both of these are `false`. Which is very odd behavior.

**Comment by AaronShea** [comment]
In fact, even `GEngine->IsInBlueprint()` is false when triggered from a button press.

**Comment by AaronShea** [comment]
https://github.com/AaronShea/BLUI/commit/73d4be57b0c1bc454e2bc6bf01a0bd9a8eee1495

This fixes it all, no need for checked in every method. Thanks!

**Comment by ArCorvus** [comment]
Thanks!

**Pull request closed without merging**
